<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FHouse.Core\FHouse.Core.csproj" />
    <ProjectReference Include="..\FHouse.Infrastructure\FHouse.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="8.6.3" />
    <PackageReference Include="AutoMapper" Version="10.1.1" />
  </ItemGroup>
</Project>
